import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Instagram } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="h-16 px-4 bg-[#ececec] flex items-center justify-between sticky top-0 z-50 w-full">
          <Link href="/">Sammen mot barnekreft</Link>
          <div className="flex gap-2">
            <Link href="/">Om oss</Link>
            <Link href="/kunstauksjon">Kunstauksjon</Link>
            <Link href="/armbaand">Armbånd</Link>
          </div>
        </header>
        <div className="grow">{children}</div>
        <footer className="h-32 bg-[#ececec] flex items-center justify-center">
          <ul>
            <li> org.nr: 123 456 789 | © 2026 Sammen mot barnekreft</li>
            <li>
              <a
                href="https://www.instagram.com/sammenmotbarnekreft"
                target="_blank"
                className="flex items-center gap-1"
              >
                <Instagram size={16} />
                Instagram
              </a>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
